// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvY3z1HshVaGJdEmq-ZwqG69VQOu_GbQE',
    appId: '1:623754082924:android:f1b4bb45c9d51bba9b3649',
    messagingSenderId: '623754082924',
    projectId: 'flutterapp-4f689',
    storageBucket: 'flutterapp-4f689.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvEYGQmBwohI8qNKlpqskI3VBVETbCy6I',
    appId: '1:623754082924:ios:0ea9a914ee135ebd9b3649',
    messagingSenderId: '623754082924',
    projectId: 'flutterapp-4f689',
    storageBucket: 'flutterapp-4f689.appspot.com',
    iosClientId: '623754082924-rpq9o16nbne3kc6qm25ndmakls9bk8tn.apps.googleusercontent.com',
    iosBundleId: 'com.lazor.app',
  );
}
